### ISSUE TITLE
Landingpage

### ISSUE THREAD

**Issue by ChsRmb** [THW-BS-Hoehenrettung/hoehenrettung#14]
On the Landingpage should be the following components:

- [x] Banner image caroussel
- [x] Possible Uses
- [x] #62
- [x] #54
- [x] #53
- [x] Map

~~Pictures (Some pictures?)~~
~~Team~~

**Comment by ChsRmb** [comment]
Image carousel is done by #26

**Comment by ichwillkeinenaccount** [comment]
All done
